# Generated by Django 4.1.7 on 2023-02-18 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Extra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("altitude", models.FloatField()),
                ("ebikes", models.IntegerField()),
                ("has_ebikes", models.BooleanField()),
                ("last_updated", models.IntegerField()),
                ("normal_bikes", models.IntegerField()),
                ("payment_terminal", models.BooleanField()),
                ("post_code", models.CharField(blank=True, max_length=50)),
                ("renting", models.IntegerField()),
                ("returning", models.IntegerField()),
                ("slots", models.IntegerField()),
                ("uid", models.CharField(max_length=50)),
            ],
            options={"ordering": ["id"],},
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Network",
            fields=[
                ("gbfs_href", models.URLField()),
                ("href", models.CharField(max_length=255)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="test1.location"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                ("empty_slots", models.IntegerField()),
                ("free_bikes", models.IntegerField()),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                (
                    "extra",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="test1.extra"
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="test1.network"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="extra",
            name="payments",
            field=models.ManyToManyField(to="test1.payment"),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="test1.network"
                    ),
                ),
            ],
        ),
    ]
