# Generated by Django 4.1.7 on 2023-02-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("nombre", models.CharField(blank=True, max_length=50)),
                ("link", models.URLField(blank=True, null=True)),
                ("tipo", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=200)),
                ("tipologia", models.CharField(blank=True, max_length=100)),
                ("titular", models.CharField(blank=True, max_length=200)),
                ("inversion", models.CharField(blank=True, max_length=50)),
                ("fecha_ingreso", models.CharField(blank=True, max_length=50)),
                ("estado", models.CharField(blank=True, max_length=50)),
                ("mapa", models.URLField(blank=True, null=True)),
            ],
            options={"ordering": ["id"],},
        ),
    ]
